# Generated by Django 3.1.3 on 2020-12-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoModel',
            fields=[
                ('productotId', models.AutoField(db_column='prod_id', primary_key=True, serialize=False, unique=True)),
                ('productoNombre', models.CharField(db_column='prod_desc', max_length=45)),
                ('productoPrecio', models.DecimalField(db_column='prod_prec', decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('productoOriginal', models.ForeignKey(db_column='prod_original', on_delete=django.db.models.deletion.CASCADE, to='inventario.productomodel')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 't_producto',
            },
        ),
        migrations.CreateModel(
            name='RazaModel',
            fields=[
                ('razaId', models.AutoField(db_column='raza_id', primary_key=True, serialize=False, unique=True)),
                ('razaNombre', models.CharField(db_column='raza_desc', max_length=45, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
                'db_table': 't_raza',
            },
        ),
        migrations.CreateModel(
            name='ProductoRazaModel',
            fields=[
                ('productoRazaId', models.AutoField(db_column='prod_raza_id', primary_key=True, serialize=False, unique=True)),
                ('productotId', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, to='inventario.productomodel')),
                ('razaId', models.ForeignKey(db_column='raza_id', on_delete=django.db.models.deletion.PROTECT, to='inventario.razamodel')),
            ],
            options={
                'verbose_name': 'Producto Raza',
                'verbose_name_plural': 'Productos Razas',
                'db_table': 't_prod_raza',
            },
        ),
    ]
