# Generated by Django 3.1.3 on 2020-12-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaModel',
            fields=[
                ('citaId', models.AutoField(db_column='cita_id', primary_key=True, serialize=False, unique=True)),
                ('citaNombre', models.CharField(db_column='cita_desc', max_length=45)),
                ('citaFecha', models.DateTimeField(db_column='cita_fecha')),
                ('citaObservaciones', models.TextField(db_column='cita_obs')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 't_cita',
            },
        ),
        migrations.CreateModel(
            name='HistorialModel',
            fields=[
                ('historialId', models.AutoField(db_column='historial_id', primary_key=True, serialize=False, unique=True)),
                ('historialFecha', models.DateTimeField(db_column='historial_fecha')),
                ('citaId', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.PROTECT, to='cita.citamodel')),
                ('productoId', models.ForeignKey(db_column='prod_id', on_delete=django.db.models.deletion.PROTECT, to='inventario.productomodel')),
            ],
        ),
    ]
