USE dbjoins;
# PARA AGREGAR UNA NUEVA COLUMNA A MI TABLA
ALTER TABLE T_EMPLEADO ADD COLUMN FEC_NAC DATETIME;
# OPCIONALMENTE PODEMOS DECIR EN QUE POSICION VA A COLOCARSE
# SE USA LA PALABRA AFTER NOMBRE_COLUMNA
ALTER TABLE T_EMPLEADO ADD COLUMN DNI INT AFTER ID_EMPLEADO;

# PARA ELIMINAR UNA COLUMNA SIEMPRE Y CUANDO NO SEA PK Y NO TENGA HERENCIA
ALTER TABLE T_EMPLEADO DROP COLUMN DNI;

# MODIFY SIRVE PARA MODIFICAR UNA COLUMNA POR SU TIPO DE DATO O SUS RESTRICCIONES
# Y EL NOMBRE DE LA COLUMNA SE USA LA PALABRA CHANGE
ALTER TABLE T_EMPLEADO MODIFY FEC_NAC DATE;
ALTER TABLE T_EMPLEADO CHANGE FEC_NAC FECNAC_EMPLEADO DATE;