# LA PALABRA RESERVERSADA USE SE USA PARA INDICAR EN QUE BASE DE DATOS VAMOS A TRABAJAR
USE LIBRERIA;
# HAY DOS FORMAS DE INSERTAR DATOS EN UNA BASE DE DATOS:
# 1. PONER LOS NOMBRE DE LOS CAMPOS SEGUIDO DE LA PALABRA RESERVADA VALUES Y SUS VALORES
# 2. DE FRENTE PONER LA PALABRA RESERVADA VALUES PERO AHI SI TENEMOS QUE INGRESAR TODOS LOS VALORES DE LOS 
# CAMPOS Y EN EL MISMO ORDEN EN EL QUE ESTA DEFININIDA LA TABLA
INSERT INTO T_AUTOR (AUTOR_ID, AUTOR_NOMB) VALUES (NULL,'JOSE');
INSERT INTO T_AUTOR VALUES ('GUILLERMO',5);
INSERT INTO T_AUTOR (AUTOR_NOMB)VALUES ('JOSE MARIA');
INSERT INTO T_AUTOR (AUTOR_NOMB, AUTOR_ID) VALUES ('GUILLERMO',5);

# PARA VISUALIZAR EL CONTENIDO DE LA TABLA SE USA EL SIGUIENTE COMANDO
# SELECT NOMBRE_CAMPO, OTRO_NOMBRE... FROM NOMBRE_TABLA [WHERE CONDICION]
# SELECT: SELECCIONAME LOS SIGUIENTES CAMPOS
# FROM: DESDE QUE TABLA O TABLAS
# WHERE: ES UN CAMPO OPCIONAL QUE NOS SIRVE PARA PONER CIERTAS RESTRICCIONES A LA CONSULTA
# SI DESEAMOS TRAER TODOS LOS CAMPOS DE LA TABLA O TABLAS USAMOS EL *
# SI NOSOTROS QUEREMOS MODIFICAR EL NOMBRE DE LA COLUMNA PERO SOLO PARA MOSTRAR USAMOS LA PALABRA RESERVADA AS Y LUEGO SU
# ALIAS Y SI ESTE TUVIESE MAS DE UNA PALABRA PONERLO ENTRE COMILLAS
SELECT AUTOR_NOMB AS 'NOMBRE AUTOR', AUTOR_ID AS 'IDENTIFICADOR DEL AUTOR' FROM T_AUTOR WHERE AUTOR_NOMB='MARIA';





