USE PLAYA_AQP;
SELECT * FROM T_VEHICULO;
# ORDER BY SIEMPRE VA AL FINAL DESPUES DE HABER DECLARADO LA (LAS) TABLA(S) Y TODOS SUS JOIN
# ADMITE DOS VALORES ASC (ASCENDENTE) O DESC (DESCENDIENTE) SI NO SE LE PONE NADA TOMA EL VALOR
# POR DEFECTO DE ASCENDENTE
SELECT * FROM T_VEHICULO ORDER BY VEH_MARCA, VEH_ANIO DESC;
SELECT * FROM T_VEHICULO ORDER BY 4 DESC, 1 ASC;

# GROUP BY SE USA PARA AGRUPAR LOS RESULTADOS DE UNA FUNCION Y QUE RESPETE SUS PARAMETROS
# https://dev.mysql.com/doc/refman/8.0/en/sql-function-reference.html
SELECT VEH_MARCA AS MARCA, COUNT(VEH_MARCA) AS TOTAL FROM t_vehiculo GROUP BY VEH_MARCA;
SELECT VEH_MARCA FROM t_vehiculo;