create database dbjoins;
use dbjoins;
CREATE TABLE t_departamento(
	id_departamento int auto_increment not null ,
    nombre_departamento varchar(100),
    primary key(id_departamento)
);
CREATE TABLE t_empleado(
	id_empleado int auto_increment not null primary key,
    nombre_empleado varchar(50),
    departamento_id int,
    foreign key (departamento_id) references t_departamento(id_departamento)
);

INSERT INTO t_departamento (nombre_departamento) VALUES ('VENTAS'), 
														('ADMINISTRACION'), 
														('MARKETING'), 
                                                        ('FINANZAS');

INSERT INTO T_EMPLEADO (NOMBRE_EMPLEADO, DEPARTAMENTO_ID) VALUES 	('JUAN PEREZ', 1),
																	('SONIA RODRIGUEZ', 3),
                                                                    ('SOFIA AGUILAR', 4),
                                                                    ('JORGE AMADO', NULL);

INSERT INTO T_EMPLEADO (NOMBRE_EMPLEADO, DEPARTAMENTO_ID) VALUES ('ISABEL MACEDO', 3);

# EL INNER JOIN NOS TRAE LA INTERSECCION DE LAS DOS O MAS TABLAS
# NOTA: SI NOSOTROS OBVIAMOS LA PALABRA JOIN ES LO MISMO
SELECT * FROM T_DEPARTAMENTO INNER JOIN T_EMPLEADO 
ON T_DEPARTAMENTO.ID_DEPARTAMENTO = T_EMPLEADO.departamento_id; 

# LEFT JOIN 
SELECT * FROM T_DEPARTAMENTO AS DEP LEFT JOIN T_EMPLEADO AS EMP
ON DEP.ID_DEPARTAMENTO = EMP.DEPARTAMENTO_ID;

# RIGHT JOIN
SELECT * FROM T_DEPARTAMENTO AS DEP RIGHT JOIN T_EMPLEADO AS EMP
ON DEP.ID_DEPARTAMENTO = EMP.DEPARTAMENTO_ID;

# FULL OUTER JOIN
SELECT * FROM T_DEPARTAMENTO AS DEP LEFT JOIN T_EMPLEADO AS EMP
ON DEP.ID_DEPARTAMENTO = EMP.DEPARTAMENTO_ID UNION
SELECT * FROM T_DEPARTAMENTO AS DEP RIGHT JOIN T_EMPLEADO AS EMP
ON DEP.ID_DEPARTAMENTO = EMP.DEPARTAMENTO_ID;

# PARA FILTRAR LAS COLUMNAS DE UN JOIN SE RECOMIENDA USAR EL NOMBRE DE LA TABLA O ALIAS Y LUEGO
# UN . Y SU NOMBRE DE LA COLUMNA (ESTO EVITARA ERRORES CUANDO TENGAMOS EL MISMO NOMBRE DE COLUMNA
# EN LAS DOS TABLAS
SELECT DEP.NOMBRE_DEPARTAMENTO, EMP.NOMBRE_EMPLEADO FROM T_DEPARTAMENTO AS DEP LEFT JOIN T_EMPLEADO AS EMP
ON DEP.ID_DEPARTAMENTO = EMP.DEPARTAMENTO_ID ;
